version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production

  node-app:
    build:
      context: ./endpoints
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - flask-app

networks:
  default:
    driver: bridge