# Use nginx as the base image
FROM nginx:alpine

# # Create the directory for SSL certificates inside the container
# RUN mkdir -p /etc/nginx/ssl

# # Copy the self-signed certificates into the container
# COPY selfsigned.crt /etc/nginx/ssl/selfsigned.crt
# COPY selfsigned.key /etc/nginx/ssl/selfsigned.key

# COPY nginx.conf /etc/nginx/nginx.conf

# # Copy the custom server block configuration (contains server directives)
# COPY default.conf /etc/nginx/conf.d/default.conf

# Copy your frontend files (static HTML, JS, CSS)
COPY . /usr/share/nginx/html

# Expose ports for HTTP and HTTPS
EXPOSE 80
# EXPOSE 443