# Use a Node.js base image
FROM node:22.9.0

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your app runs on
EXPOSE 8080

# Verify environment variables are loaded correctly
RUN echo "Verifying environment variables..." \
    && cat .env \
    && node -e "require('dotenv').config(); console.log(process.env.ACCESSKEYID, process.env.SECRETACCESSKEY)"

# Start the server
CMD ["npm", "start"]